### PR TITLE
Attempt to address intermittent s3 RequestTimeout error

### LINKED ISSUE #413: Error pushing to registry: Server error: 400 / 500
Our CI server (Jenkins) is attempting to push builds to the docker hub and sometimes fails with:
```
[workspace] $ docker push oxit/weblearn:jenkins
The push refers to a repository [oxit/weblearn] (len: 1)
3881c0e6deb2: Buffering to Disk
3881c0e6deb2: Image successfully pushed
3881c0e6deb2: Image already exists
d7cff058e4a5: Buffering to Disk
d7cff058e4a5: Image successfully pushed
0c80302861c2: Buffering to Disk
0c80302861c2: Image successfully pushed
8552f56cc885: Buffering to Disk
8552f56cc885: Image successfully pushed
fd10a9c2e70a: Buffering to Disk
fd10a9c2e70a: Image push failed
time="2015-04-22T13:11:12+01:00" level=fatal msg="Error pushing to registry: Server error: 400 trying to push oxit/weblearn blob - sha256:10d3f451806505fab44b8bfde08806adeb91b451f63e9008b57060fefa4ca1d6" 
```

This wasn't happening with 1.5.0 and only seems to have started since 1.6.0. We've now downgraded to 1.5.0 and it's all working fine.

### PR DESCRIPTION
**Pull request by stevvooe**
Addresses #413. Only close #413 after we have confirmed 400/500 errors have subsided on hub.

Signed-off-by: Stephen J Day <stephen.day@docker.com>

### CODE REVIEW

File: registry/storage/driver/s3/s3.go [hunk 1]
```diff
@@ -394,18 +395,64 @@ func (d *driver) WriteStream(path string, offset int64, reader io.Reader) (total
...
+				case *s3.Error:
+					switch err.Code {
+					case "RequestTimeout":
+						// allow retries on only this error.
+					default:
+						break loop
+					}
+				}
+
+				backoff := 100 * time.Millisecond * time.Duration(retries+1)
```
Comment (BrianBland) [inline registry/storage/driver/s3/s3.go]: Backoffs generally should be randomized, often exponential

**Comment by dmp42** [comment]
LGTM as is

**Comment by dmcgowan** [comment]
LGTM

Tested and works as designed, extreme throttling triggered timeout and was able to resume after 3 failures with turning throttling off

```
ERRO[0708] error putting part, retrying after Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.: 100ms 
ERRO[0807] error putting part, retrying after Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.: 200ms 
ERRO[0911] error putting part, retrying after Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.: 300ms 
```

File: registry/storage/driver/s3/s3.go (hunk 1 above)
Comment (stevvooe) [inline registry/storage/driver/s3/s3.go]: @BrianBland This is a good rule of thumb. Since these aren't necessarily "bursty" failures, exponential, randomized backoff isn't necessary here.

We'll take another pass at this when we clean it up.
