### PR TITLE
Fix a race condition in pull through cache population

### LINKED ISSUE #944: Registry v2 as pull-through cache eating up CPU
I configured a v2 registry mirror or pull-through cache like so:

```
registry2:
  image: registry:2
  ports:
    - 5000:5000
  links:
    - redis:REDIS
  environment:
    - REGISTRY_PROXY_REMOTEURL="https://registry-1.docker.io"
    - REGISTRY_REDIS_ADDR="REDIS:6379"
redis:
  image: redis
  expose:
    - 6379
  ports:
    - 6379:6379
```

I tried it also with host-volumes and without redis and `inmemory` settings, various versions (2, 2.1, latest); but all results are the same.

A few sequential pulls might work, but at least on two concurrent pulls, which have to be fetched by the registry, the registry container runs into some kind of idle state, eating up 70-100% of the CPU - eventually dropping out a few kB/sec of data.

Here's a longer gist of the log output https://gist.github.com/schmunk42/aeede32b28d3e94e4d30.

*Using: docker 1.8.1 with docker-machine VMs (Toolbox)*

### PR DESCRIPTION
**Pull request by RichardScothern**
Fix a race condition in pull through cache population by removing the functionality of readers joining current downloads.  Concurrent requests for the same blob will not block, but only the first instance will be comitted locally.

Add more unit tests.

This is a temporary fix. Closes #944 #913 

Signed-off-by: Richard Scothern <richard.scothern@gmail.com>

### CODE REVIEW

File: registry/proxy/proxyblobstore.go [hunk 1]
```diff
@@ -20,21 +20,15 @@ type proxyBlobStore struct {
 	localStore  distribution.BlobStore
 	remoteStore distribution.BlobService
 	scheduler   *scheduler.TTLExpirationScheduler
+	mu          sync.Mutex
+	inflight    map[digest.Digest]*inflightBlob
```
Comment (aaronlehmann) [inline registry/proxy/proxyblobstore.go]: It looks like you're using this map as a set (`inflightBlob` is an empty struct). As a slight optimization, I'd suggest using `map[digest.Digest]struct{}`. This will avoid extra garbage generated by pointers to empty structs. `map[digest.Digest]inflightBlob` would be equivalent, but `map[digest.Digest]struct{}` make it clear to readers that the map is being used as a set.

File: registry/proxy/proxyblobstore_test.go [hunk 2]
```diff
@@ -223,15 +346,12 @@ func TestProxyStoreServe(t *testing.T) {
...
-	// Remote unchanged
-	if (*remoteStats)["stat"] != remoteBlobCount && (*remoteStats)["open"] != remoteBlobCount {
-		fmt.Printf("\tlocal=%#v, \n\tremote=%#v\n", localStats, remoteStats)
-		t.Fatalf("unexpected local stats")
+	// Ensure remote unchanged
+	if (*remoteStats)["stat"] != remoteStatCount && (*remoteStats)["open"] != remoteOpenCount {
+		t.Fatalf("unexpected remote stats: %#v", remoteStats)
 	}
-
+	fmt.Println("")
```
Comment (stevvooe) [inline registry/proxy/proxyblobstore_test.go]: ?

File: registry/proxy/proxyblobstore.go [hunk 3]
```diff
@@ -42,140 +37,107 @@ func setResponseHeaders(w http.ResponseWriter, length int64, mediaType string, d
...
 	}
 
-	bw, isNew, cleanup, err := getOrCreateBlobWriter(ctx, pbs.localStore, desc)
+	proxyMetrics.BlobPush(uint64(desc.Size))
+
+	return desc, nil
+}
+
+func (pbs *proxyBlobStore) serveLocal(ctx context.Context, w http.ResponseWriter, r *http.Request, dgst digest.Digest) (bool, error) {
+	localDesc, err := pbs.localStore.Stat(ctx, dgst)
```
Comment (aaronlehmann) [inline registry/proxy/proxyblobstore.go]: I was confused about how this `Stat` prevents us from serving up an incomplete blob. After some investigation, it turns out that we upload the blob to a temporary location, and then move it once it's complete (which makes sense, because we don't know the digest in advance). On at least POSIX and S3 the rename operation should be atomic. I'm not sure about the other filesystem drivers, but if they guarantee the same semantics, this logic makes sense.

File: registry/proxy/proxyblobstore.go [hunk 4]
```diff
@@ -42,140 +37,107 @@ func setResponseHeaders(w http.ResponseWriter, length int64, mediaType string, d
...
-		pbs.scheduler.AddBlob(dgst.String(), blobTTL)
-		return nil
-	}
+}
 
-	err = streamToClient(ctx, w, desc, bw)
+func (pbs *proxyBlobStore) ServeBlob(ctx context.Context, w http.ResponseWriter, r *http.Request, dgst digest.Digest) error {
+	served, err := pbs.serveLocal(ctx, w, r, dgst)
 	if err != nil {
+		context.GetLogger(ctx).Errorf("Error serving blob from local storage: %s", err.Error())
```
Comment (aaronlehmann) [inline registry/proxy/proxyblobstore.go]: Would it make sense to fall back to serving the blob through the proxy in this case?

File: registry/proxy/proxyblobstore.go [hunk 5]
```diff
@@ -42,140 +37,107 @@ func setResponseHeaders(w http.ResponseWriter, length int64, mediaType string, d
...
+			commitErr = err
+		}
+		pbs.scheduler.AddBlob(dgst.String(), repositoryTTL)
+	}()
 
-func streamToStorage(ctx context.Context, remoteReader distribution.ReadSeekCloser, desc distribution.Descriptor, bw distribution.BlobWriter) error {
-	_, err := io.CopyN(bw, remoteReader, desc.Size)
-	if err != nil {
-		return err
+	if commitErr != nil {
```
Comment (aaronlehmann) [inline registry/proxy/proxyblobstore.go]: I'm confused by this code flow.

What we have is basically the following:

```go
var commitErr error
go func() {
    // ...
    commitErr = foo;
    // ...
}()
if commitErr != nil {
    // ...
}
```

Something seems wrong.

File: registry/proxy/proxyblobstore.go [hunk 6]
```diff
@@ -42,140 +37,107 @@ func setResponseHeaders(w http.ResponseWriter, length int64, mediaType string, d
...
 	}
 
-	return nil
-}
-
-func streamToClient(ctx context.Context, w http.ResponseWriter, desc distribution.Descriptor, bw distribution.BlobWriter) error {
-	setResponseHeaders(w, desc.Size, desc.MediaType, desc.Digest)
-
-	reader, err := bw.Reader()
+	_, err = pbs.copyContent(ctx, dgst, w)
```
Comment (aaronlehmann) [inline registry/proxy/proxyblobstore.go]: It looks like in the cold-cache case there are two independent pulls from the remote side: one to fetch the object for caching, and another to stream it to the client. Would it be difficult to use a tee writer to stream a single fetch of this content to both destinations?

**Comment by aaronlehmann** [comment]
Sorry, didn't realize you had updated this.

LGTM
