### PR TITLE
remove dependencies on resumable

### LINKED ISSUE #2697: Building private registry with go1.11 fails
Hi
I tried to build the registry with go1.11 installed and get this error:
```bash
➜  distribution git:(master) ✗ make build  
+ build
# github.com/docker/distribution/cmd/registry
github.com/docker/distribution/vendor/github.com/stevvooe/resumable/sha256.block: relocation target runtime.support_avx2 not defined
github.com/docker/distribution/vendor/github.com/stevvooe/resumable/sha256.block: relocation target runtime.support_bmi2 not defined
make: *** [Makefile:101: build] Fehler 2
```
Docker Version:
```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   f150324782
 Built:        Wed May 16 22:27:45 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.2
  Git commit:   f150324782
  Built:        Wed May 16 22:28:17 2018
  OS/Arch:      linux/amd64
  Experimental: false

```
Docker Info:
```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 43
Server Version: 18.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 41
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.122-1-MANJARO
Operating System: Manjaro Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.6GiB
Name: Carida
ID: Z34L:FUI5:J2JS:FPPW:YRKB:VPGK:ZODT:5VXQ:3XDL:RKV6:6A6W:YQQY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: snmed
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
It works fine with go 1.10.3, so there must be something with the new release. I can reproduce this issue on a different linux machine, as soon I have time I'll try the same on my macbook.

Cheers Sandro

### PR DESCRIPTION
**Pull request by davidswu**
closes #2697

### CODE REVIEW

**Comment by dmcgowan** [comment]
This is great, glad we can use the upstream hash libraries again!

Can you point to the 1.11 change related to `http.CloseNotifier`? Curious what changed there

**Comment by davidswu** [comment]
@dmcgowan `staticchecks` was failing the build about it since it is [deprecated](https://golang.org/pkg/net/http/#CloseNotifier)
Since we can just switch to `Request.Context()` I opted to clean it up rather than remove the static checks from `gometalinter`. I can revert the change and remove the checks instead if you think it's too disruptive

File: registry/storage/blobwriter_resumable.go [hunk 1]
```diff
@@ -52,20 +55,26 @@ func (bw *blobWriter) resumeDigest(ctx context.Context) error {
...
+		h.(hash.Hash).Reset()
 	} else {
 		storedState, err := bw.driver.GetContent(ctx, hashStateMatch.path)
 		if err != nil {
 			return err
 		}
 
-		if err = h.Restore(storedState); err != nil {
+		// This type assertion is safe since we already did an assertion at the beginning
+		if err = h.(encoding.BinaryUnmarshaler).UnmarshalBinary(storedState); err != nil {
```
Comment (caervs) [inline registry/storage/blobwriter_resumable.go]: Is the type assertion necessary? `h` is already asserted to be a `encoded.BinaryMarsheler`, right?

File: registry/storage/blobwriter_resumable.go [hunk 2]
```diff
@@ -52,20 +55,26 @@ func (bw *blobWriter) resumeDigest(ctx context.Context) error {
...
+			return err
+		}
+
+		state, err = h.(encoding.BinaryMarshaler).MarshalBinary()
```
Comment (caervs) [inline registry/storage/blobwriter_resumable.go]: same as above

File: context/http.go [hunk 3]
```diff
@@ -104,18 +104,6 @@ func GetRequestID(ctx context.Context) string {
 // WithResponseWriter returns a new context and response writer that makes
 // interesting response statistics available within the context.
 func WithResponseWriter(ctx context.Context, w http.ResponseWriter) (context.Context, http.ResponseWriter) {
-	if closeNotifier, ok := w.(http.CloseNotifier); ok {
```
Comment (caervs) [inline context/http.go]: Can you provide a little more context in the commit message as to why the notifier is being removed?

File: registry/storage/blobwriter_resumable.go [hunk 4]
```diff
@@ -24,12 +21,18 @@ func (bw *blobWriter) resumeDigest(ctx context.Context) error {
...
 	}
+
+	state, err := h.MarshalBinary()
+	if err != nil {
+		return err
+	}
+
 	offset := bw.fileWriter.Size()
-	if offset == h.Len() {
+	if offset == int64(len(state)) {
```
Comment (caervs) [inline registry/storage/blobwriter_resumable.go]: I don't think this is right. In a resumable hash then `Len()` is the number of bytes that have been written to the hash so far. I believe this is just giving you the len of the digest itself.

File: registry/storage/blobwriter_resumable.go [hunk 5]
```diff
@@ -52,20 +55,26 @@ func (bw *blobWriter) resumeDigest(ctx context.Context) error {
...
+
+		state, err = h.(encoding.BinaryMarshaler).MarshalBinary()
+		if err != nil {
 			return err
 		}
 	}
 
 	// Mind the gap.
-	if gapLen := offset - h.Len(); gapLen > 0 {
+	if gapLen := offset - int64(len(state)); gapLen > 0 {
```
Comment (caervs) [inline registry/storage/blobwriter_resumable.go]: Same as above

File: registry/storage/blobwriter_resumable.go (hunk 1 above)
Comment (davidswu) [reply registry/storage/blobwriter_resumable.go]: This is a `encoding.BinaryUnmarshaler`

File: registry/storage/blobwriter_resumable.go (hunk 4 above)
Comment (davidswu) [reply registry/storage/blobwriter_resumable.go]: No this is the length of the state not the length of the digest.

File: registry/storage/blobwriter_resumable.go (hunk 1 above)
Comment (caervs) [reply registry/storage/blobwriter_resumable.go]: Oh derp 😛

File: registry/storage/blobwriter_resumable.go (hunk 4 above)
Comment (davidswu) [reply registry/storage/blobwriter_resumable.go]: This is wrong though since the state length is not the offset we are looking for. We may need to implement a digester to track the offset written to the hash

File: context/http.go (hunk 3 above)
Comment (davidswu) [reply context/http.go]: `staticchecks` was failing since `http.CloseNotifier` is deprecated. So we either remove the notifier and rely on `Request.Context` instead or remove the checks. I opted for the former
