### PR TITLE
Use multipart upload API in S3 Move method

### LINKED ISSUE #886: Private registry with S3 backend: pushing big layer (5GB+) fails
**Summary**

Pushing an image having big layer fails. I know registry is capable of doing multipart upload to S3 but somehow it fails like it isn't. The big layer in subject is 6.035 GB in size.

**Error message:** 

(from docker)
```
b7d42db2a752: Pushing [==================================================>] 6.035 GB/6.035 GB
Received unexpected HTTP status: 500 Internal Server Error
```

(from registry logs) 
`The specified copy source is larger than the maximum allowable size for a copy source: 5368709120`

full line: 
```
level=error msg="unknown error completing upload: &s3.Error{StatusCode:400, Code:\"InvalidRequest\", Message:\"The specified copy source is larger than the maximum allowable size for a copy source: 5368709120\", BucketName:\"\", RequestId:\"1A35312308DA97BE\", HostId:\"4+sNkVj3TEoS7Txneh0lL6/aD4gM5T3wxrqAV9QtOyAayTVxqiG2iXAb2Xwqev1RBg0zAHPplSk=\"}" environment=prod http.request.host="<REDACTED>:5000" http.request.id=66015ba2-1ba5-4be0-92d5-8478556877fd http.request.method=PUT http.request.remoteaddr="<REDACTED>:49369" http.request.uri="/v2/some/image/blobs/uploads/d4250a63-391e-4983-9450-e407b51b1112?_state=ZB55oTS2PVNO0r3Ej2huMmqWTgwQ8Co-Ukt2-mgojQ17Ik5hbWUiOiJ0aGV1YmVyY2xvdWQvYW5zeXNfMTYuMV9jZW50b3NfNi41LTEiLCJVVUlEIjoiZDQyNTBhNjMtMzkxZS00OTgzLTk0NTAtZTQwN2I1MWIxMTEyIiwiT2Zmc2V0Ijo2MDM1Mzg1Mzc3LCJTdGFydGVkQXQiOiIyMDE1LTA4LTE3VDE5OjMwOjMyWiJ9&digest=sha256%3A68949b8b6a5f5cf5b5a2be156fe35509897a3f6747ee059206044b2715780683" http.request.useragent="docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.13.0-53-generic os/linux arch/amd64" instance.id=3da41bcb-fdb0-41ac-966d-ca4b67ec2529 service=registry vars.name="some/image" vars.uuid=d4250a63-391e-4983-9450-e407b51b1112 version=v2.1.1 
```

**Environment details**

```bash
$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64
```

```bash
$ docker info
Containers: 1
Images: 65
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 67
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 3.676 GiB
Name: fnode2
ID: WY2Y:VGXA:GTL2:L6N2:NYXJ:V4JU:Y23I:I5T5:4Q2T:URNC:YWVF:DVKO
WARNING: No swap limit support
```

```bash
$ docker exec registry registry -version
registry github.com/docker/distribution v2.1.1
```

```bash
$ docker run -i -d -p 5000:5000 --name registry -v /etc/registry/config.yml:/etc/docker/registry/config.yml:ro -e AWS_ACCESS_KEY=... -e AWS_SECRET_KEY=... distribution/registry:2.1.1
```

config.yml:
```yaml
version: 0.1
log:
  level: info
  fields:
    service: registry
    environment: prod
storage:
    s3:
      region: us-west-1
      bucket: <REDACTED>
      secure: true
      v4auth: true
      rootdirectory: /registry
http:
    addr: :5000
    secret: <REDACTED>
```

Relevant registry logs:
```
time="2015-08-17T19:30:32.918180825Z" level=info msg="response completed" environment=prod http.request.host="<REDACTED>:5000" http.request.id=b5eb0a8b-7be9-40d7-a1fd-9a6babc84a86 http.request.method=POST http.request.remoteaddr="<REDACTED>:48726" http.request.uri="/v2/some/image/blobs/uploads/" http.request.useragent="docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.13.0-53-generic os/linux arch/amd64" http.response.duration=198.363535ms http.response.status=202 http.response.written=0 instance.id=3da41bcb-fdb0-41ac-966d-ca4b67ec2529 service=registry version=v2.1.1 
<REDACTED> - - [17/Aug/2015:19:30:32 +0000] "POST /v2/some/image/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.13.0-53-generic os/linux arch/amd64"
time="2015-08-17T19:30:33.029931844Z" level=warning msg="the ResponseWriter does not implement CloseNotifier" environment=prod http.request.host="<REDACTED>:5000" http.request.id=8cbaadf0-8c96-4e90-831e-b30ab0540563 http.request.method=PATCH http.request.remoteaddr="<REDACTED>:48730" http.request.uri="/v2/some/image/blobs/uploads/d4250a63-391e-4983-9450-e407b51b1112?_state=Emav7G1FRlQJ1-t_pgF4rU5L3HOzv1Fa39dxZd2PfT57Ik5hbWUiOiJ0aGV1YmVyY2xvdWQvYW5zeXNfMTYuMV9jZW50b3NfNi41LTEiLCJVVUlEIjoiZDQyNTBhNjMtMzkxZS00OTgzLTk0NTAtZTQwN2I1MWIxMTEyIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE1LTA4LTE3VDE5OjMwOjMyLjc1MjQ5NTQxMVoifQ%3D%3D" http.request.useragent="docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.13.0-53-generic os/linux arch/amd64" instance.id=3da41bcb-fdb0-41ac-966d-ca4b67ec2529 service=registry vars.name="some/image" vars.uuid=d4250a63-391e-4983-9450-e407b51b1112 version=v2.1.1 
time="2015-08-17T19:40:17.4849859Z" level=info msg="response completed" environment=prod http.request.host="<REDACTED>:5000" http.request.id=8cbaadf0-8c96-4e90-831e-b30ab0540563 http.request.method=PATCH http.request.remoteaddr="<REDACTED>:48730" http.request.uri="/v2/some/image/blobs/uploads/d4250a63-391e-4983-9450-e407b51b1112?_state=Emav7G1FRlQJ1-t_pgF4rU5L3HOzv1Fa39dxZd2PfT57Ik5hbWUiOiJ0aGV1YmVyY2xvdWQvYW5zeXNfMTYuMV9jZW50b3NfNi41LTEiLCJVVUlEIjoiZDQyNTBhNjMtMzkxZS00OTgzLTk0NTAtZTQwN2I1MWIxMTEyIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE1LTA4LTE3VDE5OjMwOjMyLjc1MjQ5NTQxMVoifQ%3D%3D" http.request.useragent="docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.13.0-53-generic os/linux arch/amd64" http.response.duration=9m44.5491229s http.response.status=202 http.response.written=0 instance.id=3da41bcb-fdb0-41ac-966d-ca4b67ec2529 service=registry version=v2.1.1 
<REDACTED> - - [17/Aug/2015:19:30:32 +0000] "PATCH /v2/some/image/blobs/uploads/d4250a63-391e-4983-9450-e407b51b1112?_state=Emav7G1FRlQJ1-t_pgF4rU5L3HOzv1Fa39dxZd2PfT57Ik5hbWUiOiJ0aGV1YmVyY2xvdWQvYW5zeXNfMTYuMV9jZW50b3NfNi41LTEiLCJVVUlEIjoiZDQyNTBhNjMtMzkxZS00OTgzLTk0NTAtZTQwN2I1MWIxMTEyIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE1LTA4LTE3VDE5OjMwOjMyLjc1MjQ5NTQxMVoifQ%3D%3D HTTP/1.1" 202 0 "" "docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.13.0-53-generic os/linux arch/amd64"
time="2015-08-17T19:40:17.869540482Z" level=warning msg="the ResponseWriter does not implement CloseNotifier" environment=prod http.request.host="<REDACTED>:5000" http.request.id=66015ba2-1ba5-4be0-92d5-8478556877fd http.request.method=PUT http.request.remoteaddr="<REDACTED>:49369" http.request.uri="/v2/some/image/blobs/uploads/d4250a63-391e-4983-9450-e407b51b1112?_state=ZB55oTS2PVNO0r3Ej2huMmqWTgwQ8Co-Ukt2-mgojQ17Ik5hbWUiOiJ0aGV1YmVyY2xvdWQvYW5zeXNfMTYuMV9jZW50b3NfNi41LTEiLCJVVUlEIjoiZDQyNTBhNjMtMzkxZS00OTgzLTk0NTAtZTQwN2I1MWIxMTEyIiwiT2Zmc2V0Ijo2MDM1Mzg1Mzc3LCJTdGFydGVkQXQiOiIyMDE1LTA4LTE3VDE5OjMwOjMyWiJ9&digest=sha256%3A68949b8b6a5f5cf5b5a2be156fe35509897a3f6747ee059206044b2715780683" http.request.useragent="docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.13.0-53-generic os/linux arch/amd64" instance.id=3da41bcb-fdb0-41ac-966d-ca4b67ec2529 service=registry vars.name="some/image" vars.uuid=d4250a63-391e-4983-9450-e407b51b1112 version=v2.1.1 
time="2015-08-17T19:49:58.224265023Z" level=error msg="unknown error completing upload: &s3.Error{StatusCode:400, Code:\"InvalidRequest\", Message:\"The specified copy source is larger than the maximum allowable size for a copy source: 5368709120\", BucketName:\"\", RequestId:\"1A35312308DA97BE\", HostId:\"4+sNkVj3TEoS7Txneh0lL6/aD4gM5T3wxrqAV9QtOyAayTVxqiG2iXAb2Xwqev1RBg0zAHPplSk=\"}" environment=prod http.request.host="<REDACTED>:5000" http.request.id=66015ba2-1ba5-4be0-92d5-8478556877fd http.request.method=PUT http.request.remoteaddr="<REDACTED>:49369" http.request.uri="/v2some/image/blobs/uploads/d4250a63-391e-4983-9450-e407b51b1112?_state=ZB55oTS2PVNO0r3Ej2huMmqWTgwQ8Co-Ukt2-mgojQ17Ik5hbWUiOiJ0aGV1YmVyY2xvdWQvYW5zeXNfMTYuMV9jZW50b3NfNi41LTEiLCJVVUlEIjoiZDQyNTBhNjMtMzkxZS00OTgzLTk0NTAtZTQwN2I1MWIxMTEyIiwiT2Zmc2V0Ijo2MDM1Mzg1Mzc3LCJTdGFydGVkQXQiOiIyMDE1LTA4LTE3VDE5OjMwOjMyWiJ9&digest=sha256%3A68949b8b6a5f5cf5b5a2be156fe35509897a3f6747ee059206044b2715780683" http.request.useragent="docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.13.0-53-generic os/linux arch/amd64" instance.id=3da41bcb-fdb0-41ac-966d-ca4b67ec2529 service=registry vars.name="some/image" vars.uuid=d4250a63-391e-4983-9450-e407b51b1112 version=v2.1.1 
time="2015-08-17T19:49:58.587660828Z" level=error msg="response completed with error" environment=prod err.code=UNKNOWN err.detail="The specified copy source is larger than the maximum allowable size for a copy source: 5368709120" err.message="unknown error" http.request.host="<REDACTED>:5000" http.request.id=66015ba2-1ba5-4be0-92d5-8478556877fd http.request.method=PUT http.request.remoteaddr="<REDACTED>:49369" http.request.uri="/v2/some/image/blobs/uploads/d4250a63-391e-4983-9450-e407b51b1112?_state=ZB55oTS2PVNO0r3Ej2huMmqWTgwQ8Co-Ukt2-mgojQ17Ik5hbWUiOiJ0aGV1YmVyY2xvdWQvYW5zeXNfMTYuMV9jZW50b3NfNi41LTEiLCJVVUlEIjoiZDQyNTBhNjMtMzkxZS00OTgzLTk0NTAtZTQwN2I1MWIxMTEyIiwiT2Zmc2V0Ijo2MDM1Mzg1Mzc3LCJTdGFydGVkQXQiOiIyMDE1LTA4LTE3VDE5OjMwOjMyWiJ9&digest=sha256%3A68949b8b6a5f5cf5b5a2be156fe35509897a3f6747ee059206044b2715780683" http.request.useragent="docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.13.0-53-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=9m41.099918404s http.response.status=500 http.response.written=355 instance.id=3da41bcb-fdb0-41ac-966d-ca4b67ec2529 service=registry vars.name="some/image" vars.uuid=d4250a63-391e-4983-9450-e407b51b1112 version=v2.1.1 
<REDACTED> - - [17/Aug/2015:19:40:17 +0000] "PUT /v2/some/image/blobs/uploads/d4250a63-391e-4983-9450-e407b51b1112?_state=ZB55oTS2PVNO0r3Ej2huMmqWTgwQ8Co-Ukt2-mgojQ17Ik5hbWUiOiJ0aGV1YmVyY2xvdWQvYW5zeXNfMTYuMV9jZW50b3NfNi41LTEiLCJVVUlEIjoiZDQyNTBhNjMtMzkxZS00OTgzLTk0NTAtZTQwN2I1MWIxMTEyIiwiT2Zmc2V0Ijo2MDM1Mzg1Mzc3LCJTdGFydGVkQXQiOiIyMDE1LTA4LTE3VDE5OjMwOjMyWiJ9&digest=sha256%3A68949b8b6a5f5cf5b5a2be156fe35509897a3f6747ee059206044b2715780683 HTTP/1.1" 500 355 "" "docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/3.13.0-53-generic os/linux arch/amd64"
```

Docker daemon logs:
```
ESC[37mDEBUESC[0m[0081] Calling POST /images/{name:.*}/push          
ESC[34mINFOESC[0m[0081] POST /v1.20/images/<REDACTED>:5000/some/image/push?tag=latest 
ESC[37mDEBUESC[0m[0081] Trying to push <REDACTED>:5000/some/image to https://<REDACTED>:5000 v2 
ESC[37mDEBUESC[0m[0081] Error getting v2 registry: Get https://<REDACTED>/v2/: tls: oversized record received with length 20527 
ESC[37mDEBUESC[0m[0081] Trying to push <REDACTED>:5000/some/image to https://<REDACTED>:5000 v1 
ESC[37mDEBUESC[0m[0081] attempting v2 ping for registry endpoint https://<REDACTED>:5000/v2/ 
ESC[37mDEBUESC[0m[0081] attempting v1 ping for registry endpoint https://<REDACTED>:5000/v1/ 
ESC[37mDEBUESC[0m[0081] Trying to push <REDACTED>:5000/some/image to http://<REDACTED>:5000 v2 
ESC[37mDEBUESC[0m[0081] Checking "latest" against graph.Repository{"latest":"42e594508fe99d0aecfd20c0c43748e449b6da1ad275fada98af3be8bacef317"} 
ESC[37mDEBUESC[0m[0081] Pushing repository: some/image:latest 
ESC[37mDEBUESC[0m[0081] Pushing layer: 42e594508fe99d0aecfd20c0c43748e449b6da1ad275fada98af3be8bacef317 
ESC[37mDEBUESC[0m[0082] Pushing layer: 7fad4bd5b4a5d9815717a70f2024c19999624e28e70ec89d9317eddbe8890216 
ESC[37mDEBUESC[0m[0083] Pushing layer: acf7720cad891fe68f89da290a112cf45f7931ce8afe9e971470437fba791842 
ESC[37mDEBUESC[0m[0084] Pushing layer: f950e2a25d44a2c0193f6634f786ee95052080a69da1de325c0b498241bb365e 
ESC[37mDEBUESC[0m[0085] Pushing layer: 53df7285b42b6527204f1042d5c67476f1630218414a60b016a58e1fb08ea6b0 
ESC[37mDEBUESC[0m[0086] Pushing layer: ff6f1f76b3f8252931eba4e94907568334486aee6752f56c0f6f1310cd534f1b 
ESC[37mDEBUESC[0m[0087] Pushing layer: c82494ea5178a376c3ff1ca91e8148b4566ef893ad20d5a0d73eb140cd5359ab 
ESC[37mDEBUESC[0m[0088] Pushing layer: b7d42db2a75202a44b4fcf1fa38990372e155eced7dcd86fa12e9f97686b467e 
ESC[37mDEBUESC[0m[0088] [graph] TarLayer with reassembly: b7d42db2a75202a44b4fcf1fa38990372e155eced7dcd86fa12e9f97686b467e 
ESC[37mDEBUESC[0m[0088] [graph] b7d42db2a75202a44b4fcf1fa38990372e155eced7dcd86fa12e9f97686b467e is at "/var/lib/docker/aufs/mnt/b7d42db2a75202a44b4fcf1fa38990372e155eced7dcd86fa12e9f97686b467e" 
ESC[37mDEBUESC[0m[3943] rendered layer for b7d42db2a75202a44b4fcf1fa38990372e155eced7dcd86fa12e9f97686b467e of [6035385377] size 
ESC[37mDEBUESC[0m[5285] Not continuing with error: Received unexpected HTTP status: 500 Internal Server Error 
```

### PR DESCRIPTION
**Pull request by nwt**
This change to the S3 Move method uses S3's multipart upload API to copy
objects whose size exceeds a threshold.  Parts are copied concurrently.
The level of concurrency, part size, and threshold are all configurable
with reasonable defaults.

Using the multipart upload API has two benefits.

* The S3 Move method can now handle objects over 5 GB
closes #886.

* Moving most objects, and espectially large ones, is faster.  For
  example, moving a 1 GB object averaged 30 seconds but now averages 10.

Signed-off-by: Noah Treuhaft <noah.treuhaft@docker.com>

### CODE REVIEW

**Comment by RichardScothern** [comment]
Ignore the documentation build failure.

> Moving most objects, and espectially large ones, is faster. For example, moving a 1 GB object averaged 30 seconds but now averages 10.

I thought sub-5GB moves in S3 were atomic and not bound to the object size?

**Comment by nwt** [comment]
They're atomic in the sense that intermediate state is never visible, but running time is definitely a function of object size.

File: registry/storage/driver/s3-aws/s3.go [hunk 1]
```diff
@@ -565,21 +623,109 @@ func (d *driver) List(ctx context.Context, opath string) ([]string, error) {
...
+			ContentType:          d.getContentType(),
+			ACL:                  d.getACL(),
+			ServerSideEncryption: d.getEncryptionMode(),
+			SSEKMSKeyId:          d.getSSEKMSKeyID(),
+			StorageClass:         d.getStorageClass(),
+			CopySource:           aws.String(d.Bucket + "/" + d.s3Path(sourcePath)),
+		})
+		if err != nil {
+			return parseError(sourcePath, err)
+		}
```
Comment (RichardScothern) [inline registry/storage/driver/s3-aws/s3.go]: return here on success so the rest of the function can be at the top level and not in the else

File: registry/storage/driver/s3-aws/s3.go [hunk 2]
```diff
@@ -565,21 +623,109 @@ func (d *driver) List(ctx context.Context, opath string) ([]string, error) {
...
+			ServerSideEncryption: d.getEncryptionMode(),
+			StorageClass:         d.getStorageClass(),
+		})
+		if err != nil {
+			return err
+		}
+
+		numParts := (fileInfo.Size() + d.MultipartCopyChunkSize - 1) / d.MultipartCopyChunkSize
+		completedParts := make([]*s3.CompletedPart, numParts)
+		c := make(chan error, numParts)
```
Comment (RichardScothern) [inline registry/storage/driver/s3-aws/s3.go]: `errChan` (or somesuch)

File: registry/storage/driver/s3-aws/s3.go [hunk 3]
```diff
@@ -565,21 +623,109 @@ func (d *driver) List(ctx context.Context, opath string) ([]string, error) {
...
+		sem := make(chan int, d.MultipartCopyMaxConcurrency)
```
Comment (RichardScothern) [inline registry/storage/driver/s3-aws/s3.go]: `limiter` (or somesuch)

**Comment by RichardScothern** [comment]
Looks good, apart from a couple of nits.  I'll need to push this branch to upstream to run the unit tests against S3 before we merge.

**Comment by nwt** [comment]
@RichardScothern: 63468ef4a85fabb756e799c2534f0df2f3c8167c should address your comments on 6615fff1ca168549e5d561356691bb705c93b15d.

**Comment by RichardScothern** [comment]
Build is green.  LGTM 🚼
