### PR TITLE
tag service: properly handle error responses on HEAD requests by

### LINKED ISSUE #1911: Error parsing HTTP response: unexpected end of JSON input: "" when querying registry (v2.5.0)
I'm having an issue with both client and server (version v2.5.0).

I'm synchronizing a local registry dump with a remote registry and having a problem with an initial `HEAD` manifest request that is supposed to return a `manifest_unknown` error. It would've returned it in a GET, but the initial HEAD is not supposed to have a body, so the response comes back empty. The client is expecting the error in the response (`HTTP 404`) although it is the one sending `HEAD` in the first place.
Is this a bug or am I missing anything in the configuration?

I have a dead simple config.yml:

```yaml
version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /ext/registry
http:
    addr: :5000
    headers:
        X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

Also, it used to work fine previously with `v2.2.1` - when the client would make a `GET` initially. I learned support for `HEAD` requests was added in `v2.3.0` so I'm a bit baffled.

### PR DESCRIPTION
**Pull request by a-palchikov**
re-issuing requests as GET for proper error details.

Fixes #1911.

### CODE REVIEW

File: registry/client/repository.go [hunk 1]
```diff
@@ -301,43 +301,52 @@ func (t *tags) Get(ctx context.Context, tag string) (distribution.Descriptor, er
...
-		resp, err = t.client.Do(req)
 		attempts++
 		if attempts > 1 {
 			return distribution.Descriptor{}, err
 		}
 		goto check
 	default:
+		// if the response is an error - there will be no body to decode.
+		// Issue a GET request to get error details
+		resp, err = newRequest("GET")
```
Comment (dmcgowan) [inline registry/client/repository.go]: This is only needed when `attempts == 0`

Comment (a-palchikov) [inline registry/client/repository.go]: I figured `attempts` here is superfluous so I got rid of it.

File: registry/client/repository.go [hunk 2]
```diff
@@ -321,23 +323,19 @@ check:
...
+			return descriptorFromResponse(resp)
 		}
-
-		resp, err = t.client.Do(req)
-		attempts++
-		if attempts > 1 {
-			return distribution.Descriptor{}, err
-		}
-		goto check
-	default:
```
Comment (RichardScothern) [inline registry/client/repository.go]: Close the request body here

**Comment by RichardScothern** [comment]
LGTM

**Comment by a-palchikov** [comment]
@RichardScothern @codecov-io @GordonTheTurtle please let me know if there's anything else I need to do here
